# Generated by Django 4.1.3 on 2022-12-02 00:27

from django.db import migrations, models

from project import settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('valor', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('hora', models.TimeField(null=True)),
            ],
        ),
    ]
