# Generated by Django 4.1.3 on 2022-12-05 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='hora',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='valor',
            field=models.IntegerField(max_length=100),
        ),
    ]
