# Generated by Django 4.1.3 on 2022-12-05 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_person_hora_alter_person_data_alter_person_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='valor',
            field=models.IntegerField(),
        ),
    ]
