# Generated by Django 4.1.3 on 2022-12-06 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_person_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogWalker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('valor', models.IntegerField()),
                ('data', models.DateField()),
                ('hora', models.TimeField(null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='data',
        ),
        migrations.RemoveField(
            model_name='person',
            name='hora',
        ),
        migrations.RemoveField(
            model_name='person',
            name='valor',
        ),
        migrations.AddField(
            model_name='person',
            name='nomePet',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='pet',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
